server:
  port: 8081

app:
  ai:
    provider: ollmaai # or openai

spring:
  application:
    name: gen-ai-java-spring
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    vertex:
      ai:
        gemini:
          project-id: spring-ai-gemini-497207
          location: us-central1
          chat:
            options:
              model: gemini-1.5-flash
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model:  tinyllama:latest # custom-mistral-model:latest
          max-new-tokens: 512
          temperature: 0.7
logging:
  level:
    root: INFO
    com.genai.java.spring: INFO
    org.springframework.ai: INFO