server:
  port: 8081

spring:
  application:
    name: gen-ai-java-spring

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

      chat:
        options:
          model: gpt-4o

logging:
  level:
    root: INFO
    com.genai.java.spring: INFO
    org.springframework.ai: INFO